. ./demo-magic.sh

clear

DEMO_PROMPT="livefire@client-vm$"


pe "kubectl vsphere login --server wcp.corp.local --vsphere-username administrator@vsphere.local --insecure-skip-tls-verify"
pe "kubectl config get-contexts"
pe "kubectl get nodes -o wide"
pe "kubectl get ns"
pe "kubectl get pods -A"
pe "clear"
pe "kubectl get virtualmachineimages"
pe "vimcat tkg-cluster-dev.yaml"
pe "kubectl apply -f tkg-cluster-dev.yaml"
pe "kubectl get cluster,tanzukubernetescluster,virtualmachines"
pe "kubectl get cluster,tanzukubernetescluster,virtualmachines"
pe "clear"
pe "kubectl describe tanzukubernetescluster.run.tanzu.vmware.com/cluster-dev"
pe "clear"
pe "kubectl config get-contexts"
pe "kubectl vsphere login --server wcp.corp.local --vsphere-username administrator@vsphere.local --insecure-skip-tls-verify --tanzu-kubernetes-cluster-name cluster-dev --tanzu-kubernetes-cluster-namespace livefire"
pe "kubectl config use-context cluster-dev"
pe "clear"
pe "kubectl get nodes -o wide"
pe "kubectl version --short"
pe "kubectl get ns"
pe "kubectl get pods -A"
pe "clear"
pe "kubectl create clusterrolebinding psp:authenticated --clusterrole=psp:vmware-system-privileged --group=system:authenticated"
pe "kubectl create ns hipstershop"
pe "kubectl apply -f hipstershop.yaml -n hipstershop"
pe "clear"
pe "kubectl get all -n hipstershop"
pe "clear"
pe "kubectl get pods -n hipstershop"
pe "kubectl get svc -n hipstershop"
pe "kubectl get pods -n hipstershop"
pe "clear"
pe "kubectl describe pods redis-cart -n hipstershop"
pe "clear"
pe "kubectl get pvc -n hipstershop"
pe "kubectl get pv"

