apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: cluster-test
spec:
  topology:
    controlPlane:
      count: 3
      class: guaranteed-xsmall # vmclass to be used for master(s)
      storageClass: wcp-storage-policy
    workers:
      count: 5
      class: guaranteed-xsmall # vmclass to be used for workers(s)
      storageClass: wcp-storage-policy
  distribution:
    version: v1.16.8
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["10.155.4.0/22"]
      pods:
        cidrBlocks: ["10.55.16.0/20"]
